from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from datetime import datetime
from reportlab.lib.utils import simpleSplit

def draw_divider(c, y, width):
    c.setLineWidth(0.5)
    c.line(50, y, width - 50, y)

def clean_tuple_data(raw_tuple):
    try:
        return ", ".join([f"{k}={v}" for part in raw_tuple for k, v in part])
    except Exception:
        return str(raw_tuple)

def generate_pdf_report(domain, ssl_data, headers, ports, techs, file_path):
    c = canvas.Canvas(file_path, pagesize=A4)
    width, height = A4
    y = height - 50

    # Header
    # ——— HTTP Headers Section ———
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "HTTP Headers")
    y -= 20
    c.setFont("Helvetica", 12)

    if "error" in headers:
        c.setFillColorRGB(1, 0, 0)
        c.drawString(60, y, f"❌ {headers['error']}")
        c.setFillColorRGB(0, 0, 0)
        y -= 30
    else:
        max_width = width - 120  # account for 60-point left indent + 60-point right margin
        for k, v in headers.items():
            line = f"{k}: {v}"
            # split into wrapped sub-lines
            wrapped = simpleSplit(line, "Helvetica", 12, max_width)
            for i, sub in enumerate(wrapped):
                indent = 60 if i == 0 else 80
                c.drawString(indent, y, sub)
                y -= 15
            y -= 5  # small gap between headers

    c.line(50, y, width - 50, y)
    y -= 30
    c.setFont("Helvetica", 12)

    if ssl_data.get("valid"):
        c.drawString(60, y, "Certificate is valid")
        y -= 20
        issuer = clean_tuple_data(ssl_data.get("issuer", "N/A"))
        subject = clean_tuple_data(ssl_data.get("subject", "N/A"))
        c.drawString(60, y, f"Issuer: {issuer}")
        y -= 20
        c.drawString(60, y, f"Subject: {subject}")
    else:
        c.setFillColorRGB(1, 0, 0)
        c.drawString(60, y, f"{ssl_data.get('error', 'Unknown error')}")
        c.setFillColorRGB(0, 0, 0)
    y -= 30
    draw_divider(c, y, width)
    y -= 30

    # Headers
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "HTTP Headers")
    y -= 20
    c.setFont("Helvetica", 12)

    if "error" in headers:
        c.setFillColorRGB(1, 0, 0)
        c.drawString(60, y, f"{headers['error']}")
        c.setFillColorRGB(0, 0, 0)
    else:
        for k, v in list(headers.items())[:10]:
            c.drawString(60, y, f"{k}: {v}")
            y -= 15
    y -= 30
    draw_divider(c, y, width)
    y -= 30

    # Port Scan
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Open Ports")
    y -= 20
    c.setFont("Helvetica", 12)

    if isinstance(ports, list):
        if ports:
            port_str = ', '.join(map(str, ports))
            c.drawString(60, y, port_str)
        else:
            c.drawString(60, y, "No open ports detected.")
    else:
        c.setFillColorRGB(1, 0, 0)
        c.drawString(60, y, f"{ports.get('error', 'Scan failed')}")
        c.setFillColorRGB(0, 0, 0)
    y -= 30
    draw_divider(c, y, width)
    y -= 30

    # Tech Stack
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Detected Tech Stack")
    y -= 20
    c.setFont("Helvetica", 12)
    if techs:
        c.drawString(60, y, ", ".join(techs))
    else:
        c.drawString(60, y, "Unknown")
    y -= 30
    draw_divider(c, y, width)
    y -= 30

    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 30, "Report generated by CyberGuard Lite")
    c.drawRightString(width - 50, 30, datetime.now().strftime('%Y-%m-%d %H:%M:%S'))

    c.save()